English:
  font1: Noto/English/Montserrat-Regular.ttf
  font2: Noto/English/Montserrat-Bold.ttf
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Marathi:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Tamil:
  font1: Noto/Tamil/NotoSansTamil-Regular.ttf 
  font2: Noto/Tamil/NotoSansTamil-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Hindi:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Urdu:
  font1: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  font2: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Malayalam:
  font1: Noto/Malayalam/NotoSansMalayalam-Regular.ttf 
  font2: Noto/Malayalam/NotoSansMalayalam-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Hindi:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Bangla:
  font1: Noto/Bengali/NotoSansBengali-Regular.ttf 
  font2: Noto/Bengali/NotoSansBengali-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Gujarati:
  font1: Noto/Gujarati/NotoSansGujarati-Regular.ttf 
  font2: Noto/Gujarati/NotoSansGujarati-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Punjabi:
  font1: Noto/Punjabi/NotoSansGurmukhi-Regular.ttf 
  font2: Noto/Punjabi/NotoSansGurmukhi-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Telugu:
  font1: Noto/Telugu/NotoSansTelugu-Regular.ttf 
  font2: Noto/Telugu/NotoSansTelugu-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Odia:
  font1: Noto/Odia/NotoSansOriya-Regular.ttf 
  font2: Noto/Odia/NotoSansOriya-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Kannada:
  font1: Noto/Kannada/NotoSansKannada-Regular.ttf 
  font2: Noto/Kannada/NotoSansKannada-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Asamese:
  font1: Noto/Bengali/NotoSansBengali-Regular.ttf 
  font2: Noto/Bengali/NotoSansBengali-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Khasi:
  font1: Noto/English/Montserrat-Regular.ttf 
  font2: Noto/English/Montserrat-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Nepali:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Manipuri:
  font1: Noto/Bengali/NotoSansBengali-Regular.ttf 
  font2: Noto/Bengali/NotoSansBengali-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Konkani:
  font1: Noto/Devanagari/NotoSansDevanagari-Regular.ttf 
  font2: Noto/Devanagari/NotoSansDevanagari-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
Kashmiri:
  font1: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf 
  font2: Noto/Urdu/NotoNastaliqUrdu-Bold.ttf 
  size1: 23
  size2: 18
  size3: 23
  size4: 26
  size5: 14
  size6: 23
  size7: 15
